### ISSUE TITLE
exit code 1 from chr22

### ISSUE THREAD

**Issue by weinstockj** [auerlab/ad2vcf#2]
Logs from ad2vcf look like this. After looking at a few logs, they are mostly failing in chr22 in different places:

> Read 2 duplicate calls at chr chr1 pos 72303448.
> Read 2 duplicate calls at chr chr1 pos 72332644.
> Read 2 duplicate calls at chr chr1 pos 223150300.
> Finished chromosome, 161421 calls processed.
> Read 2 duplicate calls at chr chr2 pos 43862086.
> Finished chromosome, 168185 calls processed.
> Finished chromosome, 151241 calls processed.
> Finished chromosome, 147767 calls processed.
> Finished chromosome, 136648 calls processed.
> Finished chromosome, 132811 calls processed.
> Finished chromosome, 123353 calls processed.
> Finished chromosome, 116200 calls processed.
> Finished chromosome, 88436 calls processed.
> Finished chromosome, 99607 calls processed.
> Read 2 duplicate calls at chr chr11 pos 54526860.
> Read 2 duplicate calls at chr chr11 pos 54527533.
> Finished chromosome, 104974 calls processed.
> Finished chromosome, 94820 calls processed.
> Finished chromosome, 79399 calls processed.
> Finished chromosome, 65078 calls processed.
> Finished chromosome, 57815 calls processed.
> Read 2 duplicate calls at chr chr16 pos 82130802.
> Finished chromosome, 62381 calls processed.
> Read 2 duplicate calls at chr chr17 pos 46301965.
> Finished chromosome, 54068 calls processed.
> Finished chromosome, 53703 calls processed.
> Finished chromosome, 45977 calls processed.
> Read 2 duplicate calls at chr chr20 pos 24923261.
> Finished chromosome, 44455 calls processed.
> Finished chromosome, 28465 calls processed.
> ./ad2vcf/bin/ad2vcf: vcf_read_static_fields(): Got EOF reading CHROM.
> This is where we should reach EOF.
> ./ad2vcf/bin/ad2vcf: vcf_read_static_fields(): Got EOF reading CHROM.
> This is where we should reach EOF.
> Loop terminated with more_alignments = 1, new calls = 0
> ===
> rname = chr22 pos=50805816 len=151 >TGGAGCTTGCATTGAGCCGAGATCGCGCCACTGCAGTCCGCAGTCCGGCCTGGGCGACAGAGCGAGACTC>CGTCTCAAAAAAAAAAAAAAAAAAAAAGATGCCCCAATCATCATTCACTCTGCAATAAAAATGTCAGAATAT>TGCTAGCTA
> vcf_pos = 50805809, vcf_chromosome = chr22

**Comment by outpaddling** [comment]
These are not errors, they're informational messages that indicate a successful run.
Thanks for the report, though.

**Comment by weinstockj** [comment]
So should I ignore exit code 1?

**Comment by outpaddling** [comment]
Do any of them terminate without the following message?
```
Got EOF reading CHROM.
This is where we should reach EOF.
```
If you see that, then the run was successful.  I'd then have to explore why the exit code is non-zero.

**Comment by weinstockj** [comment]
Yes, some of them terminate without that message. 

> "Read 2 duplicate calls at chr chr1 pos 241197316.                                                                                                                                                                                            Finished chromosome, 162714 calls processed.                                                                                                                                                                                                 ./ad2vcf/bin/ad2vcf: Invalid alignment position: chr1 "

Looking to that VCF, this line looks like:

> chr1    241197316       .       G       A       .       .       .       GT:AD:DP        1|0:5,20:25
> chr1    241197316       .       G       T       .       .       .       GT:AD:DP        1|0:5,0:5

This looks like a multi-allelic SNP. Does ad2vcf handle this case?
