### ISSUE TITLE
Unused shared library error while building under archlinux

### ISSUE THREAD

**Issue by kbipinkumar** [auerlab/ad2vcf#4]
hi i was attempting to build ad2vcf under archlinux. i am able to compile and package ad2vcf, however the resulting binary shows following error

```
Unused shared library '/usr/lib/libxtend.so.2' by file ('usr/bin/ad2vcf')
```
i am assuming libxtend.so is not needed by ad2vcf binary but is still referencing to it, can this be avoided?

**Comment by outpaddling** [comment]
Did you try using pkgsrc as described in the README?  Ad hoc installs are not supported, except for development purposes.

**Comment by kbipinkumar** [comment]
using `pkgsrc` might be the right idea but my Intention was to create package archive that can be installed/removed by archlinux's native package manager `pacman`.

**Comment by outpaddling** [comment]
In that case, you should create a libxtend package and a biolibc package first.  The pacman ad2vcf package should list them as build and runtime dependencies, so they are installed before it attempts to build ad2vcf.  I don't know anything about pacman, but it should be something similar to the LIB_DEPENDS variable in the FreeBSD port:

https://github.com/outpaddling/freebsd-ports-wip/blob/master/ad2vcf/Makefile

The biolibc package should also depend on libxtend.

I would assume that pacman provides the standard install prefix to the build via `${PREFIX}` or `${LOCALBASE}` via the environment or a make argument, like many other package managers.  If not, just set PREFIX to the install prefix of libxtend and biolibc.

Let me know if you have any other questions, and thanks for adding the pacman package.

**Comment by kbipinkumar** [comment]
the archlinux packages are built using PKGBUILD scripts([wiki](https://wiki.archlinux.org/title/Creating_packages)), which are essentially shell scripts, read by `makepkg` command.  basically, it follows the standard unix install workflow of 

```
./configure
make
make install
```
albeit in a fakeroot environment. Below is the PKGBUILD i am using for ad2vcf. 

```
# Maintainer: Bipin Kumar 

pkgname=ad2vcf
pkgver=0.1.6
pkgrel=1
pkgdesc="Tool to add allelic depth info from a SAM stream to a VCF file"
arch=('x86_64')
url="https://github.com/auerlab/ad2vcf"
license=('BSD-2')
depends=('biolibc')
source=("$pkgname-$pkgver.tar.gz::https://github.com/auerlab/$pkgname/archive/refs/tags/$pkgver.tar.gz")
sha256sums=('fbed1e32504dbc6975cb124792d12e48576ed799ac148aa3b6beed33a67bdf98')

package() {
  cd "$pkgname-$pkgver"
  make PREFIX="$pkgdir/usr" MANPREFIX="$pkgdir/usr/share" clean depend install
  install -Dm644 LICENSE -t "$pkgdir/usr/share/licenses/$pkgname"
}
```
the execution of above script by `makepkg` will result in zstd compressed archive package that during installation by `pacman` will extract files to appropriate location such as /usr/lib and /usr/bin along installing any dependentt packages as mentioned in `PKGBUILD`
 
as you can see i have given `biolibc` as dependency in the `PKGBUILD` so that it will be installed prior to building/installation of ad2vcf. Are you saying i need to add `libxtend` as a dependency as well?

i have made similar packages for biolibc and libxtend as well. those packages install libraries to /usr/lib and headers to /usr/include/$pkgname and binaries to /usr/bin as suggested by standard archlinux package guidlines

**Comment by outpaddling** [comment]
Again, I don't know pacman, but my impression is that listing libxtend explicitly is probably not necessary if it's an indirect dependency via biolibc.  That would be a question for the pacman developer community, though.  I list it in the FreeBSD port Makefile mainly for documentation.  

You'll also need `VERSION` set in your make environment if you want `ad2vcf --version` to work.

BTW, let me know when the packages are actually available to pacman users, and I'll mention it in the READMEs.

**Comment by outpaddling** [comment]
Regarding the unused libxtend.so, did you statically linked biolibc and libxtend in the original build?  ad2vcf does use functions from libxtend via biolibc.

```
cc -o ad2vcf ad2vcf.o  -L/usr/local/lib -lbiolibc
ld: error: /usr/local/lib/libbiolibc.so: undefined reference to tsv_read_field [--no-allow-shlib-undefined]
ld: error: /usr/local/lib/libbiolibc.so: undefined reference to xt_malloc [--no-allow-shlib-undefined]
ld: error: /usr/local/lib/libbiolibc.so: undefined reference to dsv_read_field [--no-allow-shlib-undefined]
ld: error: /usr/local/lib/libbiolibc.so: undefined reference to dsv_read_field_malloc [--no-allow-shlib-undefined]
ld: error: /usr/local/lib/libbiolibc.so: undefined reference to xt_realloc [--no-allow-shlib-undefined]
ld: error: /usr/local/lib/libbiolibc.so: undefined reference to tsv_read_field_malloc [--no-allow-shlib-undefined]
ld: error: /usr/local/lib/libbiolibc.so: undefined reference to dsv_skip_rest_of_line [--no-allow-shlib-undefined]
ld: error: /usr/local/lib/libbiolibc.so: undefined reference to tsv_skip_field [--no-allow-shlib-undefined]
ld: error: /usr/local/lib/libbiolibc.so: undefined reference to strblank [--no-allow-shlib-undefined]
ld: error: /usr/local/lib/libbiolibc.so: undefined reference to xt_fclose [--no-allow-shlib-undefined]
ld: error: /usr/local/lib/libbiolibc.so: undefined reference to tsv_skip_rest_of_line [--no-allow-shlib-undefined]
ld: error: /usr/local/lib/libbiolibc.so: undefined reference to ltostrn [--no-allow-shlib-undefined]
```

**Comment by kbipinkumar** [comment]
> Regarding the unused libxtend.so, did you statically linked biolibc and libxtend in the original build? ad2vcf does use functions from libxtend via biolibc.

i have used only the default build commands from git README as below

```
make PREFIX="$pkgdir/usr" MANPREFIX="$pkgdir/usr/share" clean depend install
```
the only difference is the use of `$pkgdir` in the prefix so as to ensure the build process stays within the fakeroot environment (which replicates standard linux filesystem hierarchy). so the linking to biolibc or libxtend will determined by the makefile itself

**Comment by outpaddling** [comment]
> > Regarding the unused libxtend.so, did you statically linked biolibc and libxtend in the original build? ad2vcf does use functions from libxtend via biolibc.
> 
> i have used only the default build commands from git README as below
> 
> ```
> make PREFIX="$pkgdir/usr" MANPREFIX="$pkgdir/usr/share" clean depend install
> ```

Perhaps your linker is ignoring unresolved references in shared objects on the assumption that they will be resolved at runtime.  No matter, as long as the packages work.
Note that the Makefile respects DESTDIR.  It looks like your pkgdir is the same thing, so it might be a little cleaner to use
`DESTDIR=$pkgdir PREFIX=/usr MANPREFIX=/usr/share`

**Comment by outpaddling** [comment]
BTW, do you actually have a use for ad2vcf?  Of all the tools I've written so far, I considered this the most likely to never be used by another person.  It's a rather esoteric need, specific to calling mCAs with haplohseq using some specific VCFs that are missing allelic depths.

**Comment by kbipinkumar** [comment]
> BTW, do you actually have a use for ad2vcf? Of all the tools I've written so far, I considered this the most likely to never be used by another person. It's a rather esoteric need, specific to calling mCAs with haplohseq using some specific VCFs that are missing allelic depths.

sorry for the delay in replying. i personally do not have any use of ad2vcf. i do contribute to packaging efforts of a [third party repository](https://github.com/BioArchLinux/Packages) of archlinux where they aim to include as many bioinformatics tools as possible and ad2vcf happens to be one of the many tools that are in their list of [objectives](https://github.com/BioArchLinux/Packages/projects/3#card-80745536)

being a beginner i started off with tools with simpler build processes before moving on to complex ones

**Comment by outpaddling** [comment]
> > BTW, do you actually have a use for ad2vcf? Of all the tools I've written so far, I considered this the most likely to never be used by another person. It's a rather esoteric need, specific to calling mCAs with haplohseq using some specific VCFs that are missing allelic depths.
> 
> sorry for the delay in replying. i personally do not have any use of ad2vcf. i do contribute to packaging efforts of a [third party repository](https://github.com/BioArchLinux/Packages) of archlinux where they aim to include as many bioinformatics tools as possible and ad2vcf happens to be one of the many tools that are in their list of [objectives](https://github.com/BioArchLinux/Packages/projects/3#card-80745536)
> 
> being a beginner i started off with tools with simpler build processes before moving on to complex ones

Interesting.  If you want more practice, the other tools on the auerlab site are more generally useful than ad2vcf and the packages will be nearly identical.

**Comment by outpaddling** [comment]
> arch=('x86_64')

Just looked this over again and I wonder if this is restricting the package to x86_64.  All of the software on the auerlab and outpaddling Github sites should work on any CPU.

**Comment by kbipinkumar** [comment]
> Interesting. If you want more practice, the other tools on the auerlab site are more generally useful than ad2vcf and the packages will be nearly identical.

could you point to suitable candidate tools? I will look into packaging the same at the earliest.

> Just looked this over again and I wonder if this is restricting the package to x86_64. All of the software on the auerlab and outpaddling Github sites should work on any CPU.

the issue has been addressed with upcoming builds. (usually it will take upto 24 hours for package to be build once the updated `PKGBUILD` is added to the repo)

> BTW, let me know when the packages are actually available to pacman users, and I'll mention it in the READMEs.

The easiest way is add [Bioarchlinux](https://github.com/BioArchLinux/Packages) repo to pacman mirrors as per their instructions. This will ensure all dependencies are met during installation. *(Note: the following steps require elevated privileges either as root user or by sudo)*

Add the following content to the `/etc/pacman.conf`
```
[bioarchlinux]
Server = https://repo.bioarchlinux.org/$arch
```
You can replace the `https://repo.bioarchlinux.org/$arch` with any mirror in [mirrorlist](https://raw.githubusercontent.com/BioArchLinux/mirror/main/mirrorlist.bio)

install GPG keyring to use bioarchlinux
```shell
# pacman-key --recv-keys B1F96021DB62254D
# pacman-key --finger B1F96021DB62254D
# pacman-key --lsign-key B1F96021DB62254D
```

update the database
```shell
# pacman -Syy
```

install packages. eg: ad2vcf
```shell
# pacman -S ad2vcf
```

The longer way is to use Arch User Repository. However this process is little more involved as the dependencies that are not available in main archlinux repositories such as `libxtend` and `biolibc` will needed to be installed in the proper order as below. *(Note: `makepkg` command should not run with root privileges)*

1. libxtend 
   
   ```shell
   # git clone https://aur.archlinux.org/libxtend.git
   # cd libxtend
   # makepkg -si
   ```
2. biolibc 
   
   ```shell
   # git clone https://aur.archlinux.org/biolibc.git
   # cd biolibc
   # makepkg -si
   ```
3. ad2vcf   
   ```shell
   # git clone https://aur.archlinux.org/ad2vcf.git
   # cd ad2vcf
   # makepkg -si
   ```

**Comment by outpaddling** [comment]
> The easiest way is add [Bioarchlinux](https://github.com/BioArchLinux/Packages) repo to pacman mirrors as per their instructions. This will ensure all dependencies are met during installation. _(Note: the following steps require elevated privileges either as root user or by sudo)_

I just meant that I would mention in the libxtend/biolibc/ad2vcf READMEs that packages are available in BioArchLinux and point them to the BioArchLinux website.

**Comment by outpaddling** [comment]
> > Interesting. If you want more practice, the other tools on the auerlab site are more generally useful than ad2vcf and the packages will be nearly identical.
> 
> could you point to suitable candidate tools? I will look into packaging the same at the earliest.

I'd recommend biolibc-tools, fastq-trim, fasda, peak-classifier, and vcf-split as the most generally useful tools for now.
Thanks again...

**Comment by outpaddling** [comment]
Added BioArchLinux links to the READMEs for libxtend, biolibc, and ad2vcf.
