### ISSUE TITLE
Containerized ad2vcf

### ISSUE THREAD

**Issue by jonathonl** [auerlab/ad2vcf#5]
Would it be possible for you to provide a Singularity container or Docker image for ad2vcf? FreeBSD isn't an option for us and the non-FreeBSD instructions are not working. After installing Pkgsrc (selected "current" and default prefix), the `~/Pkgsrc/biology/ad2vcf` does not exist.

**Comment by outpaddling** [comment]
No, there is no reason to containerize this software.  Containers are often used as an alternative to understanding and fixing build issues, but doing the latter should be simple here.  All of the software here is well-tested on multiple BSDs, Linux distros and macOS using pkgsrc.  I'd be happy to help you troubleshoot any issues you're having with pkgsrc.

First, did you mean to write ~/Pkgsrc/pkgsrc/biology/ad2vcf?

**Comment by jonathonl** [comment]
No, the path I referenced is what I meant to write. I'm following instructions at https://github.com/auerlab/ad2vcf/blob/e84275be567fefed5f3f8f0192bac8c8806210ff/README.md?plain=1#L124-L126

**Comment by outpaddling** [comment]
I see...  That's a typo that has apparently been in a few of my repos since the beginning, and nobody ever mentioned before.  It's fixed now.  Let me know if you run into any other issues.  Thanks for the heads-up.
